# Site settings
title: cSploit
email: blog@csploit.org
description: "Official cSploit blog"
baseurl: "/"
url: "http://www.csploit.org"
twitter_username: cSploit
github_username: cSploit

# Build settings
markdown: redcarpet
permalink: /:title/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "article"
      author: "tux_mind"

gems:
  - jemoji
